package dk.comet.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.sql.PreparedStatement;
import java.sql.ResultSet;

@Service("nationality")
public class NationalityResponse {

    /**
     * A pointer we can use to refer to springs JdbcTemplate
     * so we can use the same database connection and can avoid
     * creating multiple connections that overlap eachother
     *
     * @author 		Stonie
     */
    private final JdbcTemplate jdbcTemplate;

    /**
     * An autowired method that gets the jdbcTemplate
     * from spring so we can use the same database
     * connection and can avoid creating multiple
     * connections that overlap eachother
     *
     * @param  		jdbcTemplate autogenerated by Spring using Autowired annotation
     * @author 		Stonie
     */
    @Autowired
    public NationalityResponse(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public String getNationalityResponseBasedOnCountry(String nationality, String country){
        try {
            PreparedStatement sql = jdbcTemplate.getDataSource().getConnection().prepareStatement("SELECT "+country+" FROM `nationality` WHERE Country=?;");
            sql.setString(1, nationality);
            ResultSet result = sql.executeQuery();
            result.next();
            String HtmlPage = result.getString(country);
            sql.close();
            result.close();
            return HtmlPage;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

}
